In [1]:
import seaborn as sns

In [2]:
df = sns.load_dataset('titanic')
df.columns


Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [3]:
idade = df['age']
familiares = df['sibsp']
tarifa = df['fare']
print(idade.isnull().sum())
print(familiares.isnull().sum())
print(tarifa.isnull().sum())

177
0
0


In [4]:
idade_limpa = idade.dropna()
print(idade_limpa.isnull().sum())

0


In [5]:
print(familiares.shape)
print(tarifa.shape)
print(idade_limpa.shape)

(891,)
(891,)
(714,)


In [6]:
f = familiares.values.reshape(-1, 1)
t = tarifa.values.reshape(-1, 1)
i = idade_limpa.values.reshape(-1, 1)

In [7]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import MaxAbsScaler
from sklearn.preprocessing import StandardScaler

normalizador_minmax = MinMaxScaler()
normalizador_maxabs = MaxAbsScaler()
normalizador_standard = StandardScaler()

normalizador_minmax.fit(f)
normalizador_maxabs.fit(f)
normalizador_standard.fit(f)

familiares_normalizados_minmax = normalizador_minmax.transform(f)
familiares_normalizados_maxabs = normalizador_maxabs.transform(f)
familiares_normalizados_standard = normalizador_standard.transform(f)

# Ver resultados
print("Dados originais")
print(f[0:5])
print()

print("Dados normalizados")
print("Dados normalizados minmax:")
print(familiares_normalizados_minmax[0:5])
print()
print("Dados normalizados maxabs:")
print(familiares_normalizados_maxabs[0:5])
print()
print("Dados normalizados standard:")
print(familiares_normalizados_standard[0:5])
print()

if familiares_normalizados_minmax.all() == familiares_normalizados_maxabs.all():
    print("Os dados normalizados com MinMaxScaler e MaxAbsScaler são iguais.")

else:
    print("Os dados normalizados com MinMaxScaler e MaxAbsScaler são diferentes.")

Dados originais
[[1]
 [1]
 [0]
 [1]
 [0]]

Dados normalizados
Dados normalizados minmax:
[[0.125]
 [0.125]
 [0.   ]
 [0.125]
 [0.   ]]

Dados normalizados maxabs:
[[0.125]
 [0.125]
 [0.   ]
 [0.125]
 [0.   ]]

Dados normalizados standard:
[[ 0.43279337]
 [ 0.43279337]
 [-0.4745452 ]
 [ 0.43279337]
 [-0.4745452 ]]

Os dados normalizados com MinMaxScaler e MaxAbsScaler são iguais.


In [8]:
normalizador_minmax = MinMaxScaler()
normalizador_maxabs = MaxAbsScaler()
normalizador_standard = StandardScaler()

normalizador_minmax.fit(t)
normalizador_maxabs.fit(t)
normalizador_standard.fit(t)

tarifas_normalizados_minmax = normalizador_minmax.transform(t)
tarifas_normalizados_maxabs = normalizador_maxabs.transform(t)
tarifas_normalizados_standard = normalizador_standard.transform(t)

# Ver resultados
print("Dados originais")
print(t[0:1])
print()

print("Dados normalizados")
print("Dados normalizados minmax:")
print(tarifas_normalizados_minmax[0:10])
print()
print("Dados normalizados maxabs:")
print(tarifas_normalizados_maxabs[0:10])
print()
print("Dados normalizados standard:")
print(tarifas_normalizados_standard[0:5])
print()

if tarifas_normalizados_minmax.all() == tarifas_normalizados_maxabs.all():
    print("Os dados normalizados com MinMaxScaler e MaxAbsScaler são iguais.")

else:
    print("Os dados normalizados com MinMaxScaler e MaxAbsScaler são diferentes.")

Dados originais
[[7.25]]

Dados normalizados
Dados normalizados minmax:
[[0.01415106]
 [0.13913574]
 [0.01546857]
 [0.1036443 ]
 [0.01571255]
 [0.0165095 ]
 [0.10122886]
 [0.04113566]
 [0.02173075]
 [0.05869429]]

Dados normalizados maxabs:
[[0.01415106]
 [0.13913574]
 [0.01546857]
 [0.1036443 ]
 [0.01571255]
 [0.0165095 ]
 [0.10122886]
 [0.04113566]
 [0.02173075]
 [0.05869429]]

Dados normalizados standard:
[[-0.50244517]
 [ 0.78684529]
 [-0.48885426]
 [ 0.42073024]
 [-0.48633742]]

Os dados normalizados com MinMaxScaler e MaxAbsScaler são iguais.


In [9]:
normalizador_minmax = MinMaxScaler()
normalizador_maxabs = MaxAbsScaler()
normalizador_standard = StandardScaler()

normalizador_minmax.fit(i)
normalizador_maxabs.fit(i)
normalizador_standard.fit(i)

idade_normalizados_minmax = normalizador_minmax.transform(i)
idade_normalizados_maxabs = normalizador_maxabs.transform(i)
idade_normalizados_standard = normalizador_standard.transform(i)

# Ver resultados
print("Dados originais")
print(i[0:5])
print()

print("Dados normalizados")
print("Dados normalizados minmax:")
print(idade_normalizados_minmax[0:5])
print()
print("Dados normalizados maxabs:")
print(idade_normalizados_maxabs[0:5])
print()
print("Dados normalizados standard:")
print(idade_normalizados_standard[0:5])
print()

if idade_normalizados_minmax.all() == idade_normalizados_maxabs.all():
    print("Os dados normalizados com MinMaxScaler e MaxAbsScaler são iguais.")

else:
    print("Os dados normalizados com MinMaxScaler e MaxAbsScaler são diferentes.")

Dados originais
[[22.]
 [38.]
 [26.]
 [35.]
 [35.]]

Dados normalizados
Dados normalizados minmax:
[[0.27117366]
 [0.4722292 ]
 [0.32143755]
 [0.43453129]
 [0.43453129]]

Dados normalizados maxabs:
[[0.275 ]
 [0.475 ]
 [0.325 ]
 [0.4375]
 [0.4375]]

Dados normalizados standard:
[[-0.53037664]
 [ 0.57183099]
 [-0.25482473]
 [ 0.36516706]
 [ 0.36516706]]

Os dados normalizados com MinMaxScaler e MaxAbsScaler são diferentes.


O que observamos de interessante é que duas de nossas normalizações deram resultados iguais para 2 conjuntos de dados (Tarifa e número de familiares a bordo): A normalização por máximo absoluto e a normalização por mínimo e máximo. Isso acontece porque o valor mínimo nesses conjutos é 0, pois não tem como existir um valor negativo para esse conjunto de dados. 

$$ n_i = \frac{x_i}{\max(|x|)} $$

$$ m_i = \frac{x_i - \min(x_i)}{\max(x) - \min(x)} $$

Se analizarmos a fórmula acima, quando o valor mínimo é 0 as duas se tornam iguais, dessa forma os dados normalizados ficam os mesmos.

No caso da idadde, não existe um valor mínimo de 0, então a normalização por máximo absoluto e a normalização por mínimo e máximo deram resultados diferentes.